---
title: "First Knit"
author: "Celina Wilson"
date: "`r Sys.Date()`"
output:
  pdf_document:
    toc: yes
    toc_depth: '5'
  html_document:
    number_sections: yes
    toc: yes
    toc_depth: 5
---

# A Little Survey

Here are just a few questions so I can get to know you and so you can get practice submitting an assignment in Canvas.  For each question, insert your answer underneath. Make sure each answer is at the minimum a complete sentence with correctly spelled words and correct puncuation. 

## A short history of you.  
Where did you attend High School, and did you graduate? Compare english class to math, is one easier for you than the other? Finally which subject did you do the best in? Your answer should have at least two sentences devoted to each question.  
  
### my answer     
  I went to multiple Highschools but I graduated from a charter school called R.rex Paris. I graduated in the charter school in 2020, it was particularlly hard for me because I didn't have a stable home .In my experience English is easier for me because I read a lot,and visited libraries many times after school. But math is more fulfilling to learn,especially because I struggled with math all of my school career up until my last year of highschool.

     


## Your computer and your and its capability?  
 For this class  you need a computer you can use at home.  So, what kind is it (windows, Apple, Linux)?  On a scale of 1 to 10, where 1 is a total dummy (doesn't know a mouse from a keyboard) and 10 is a complete geek (knows computer stuff in and out) How do you rate yourself?  You also need to have have internet access. How is your connection to the internet where you live?

### my answer   
   I have a Chromebook for my computer, and although it isn't the perfect computer it does what I need it to do. I rate my self a 3 or four when it comes to computer knowlegde because I can print and fix an error or two but i'm not advanced by any means.My computor access is okay but not great

## Others and You?   
What name do you prefer to be called by your classmates and instructor, if your buddys call you something but you want people in the class to call you something else - what would that be? 

### my answer     
 I prefer to be called my Birth name Celina by my classmates and instructors. My nicknames are Nina and Baby Celina because I'm a junior. I only prefer my family to call me by my nicknames.I wouldn't want anyone else to call me by anything but my first name in the class.
   
 




## Aspirations?   
What do you want to achieve in life?  What college subject do you think would be of the greatest interest to you? What degree or certificate are you trying to achieve?

### my answer     
  I want to achieve a big support group and be able to live comfortably in life. Like I mentioned before I haven't had a stable home since I was 12 and have always been on my own without a real support group. So I want to be able to earn a lot of money and gain a support group.I think the college subject that would be the most interesting is biology. I like being able to learn hands on and being able to do dissections is one of those ways.I am trying to achieve multiple degrees. Including a bachelors,masters,and eventually a doctorate.I want to be able to gain as much information as possible during my college years.
   
 




## Past adventures?  
Have you ever gone to foreign countries, if so which ones, if not Where might you go in the future?  Have you ever been in the military, if so which branch, if not which branch would you choose if you got drafted, and why?

### my answer     
  I have never been to any foreign countries but in the near future I will be going to France. I have a great friend who lives there,I would also love to visit Switzerland.I have never been to the military but if I had tp join,I'd probably join the Navy. Because i've always liked the water and would like the opportunity to travel.
   
  




## Why are you taking Statistics?  
Did you take Math 115 or Math 116 ?  Did you know Math 115 only satisfies a general education requirement but that Math 116 counts as taking statistics in several transfer institutions??  
What grade do you need to attain in stats to not upset your future plans, What is your plan?  
 

### my answer     
  I did not take any previous math courses but I will be taking math 116 now that I know it transfers to different colleges.I need to get an A to satisfy my plan because I do plan on transferring to different colleges after attending avc and obtaining multiple degrees.
   
 






  




